### ISSUE TITLE
Recent react 15.0.2 upgrade breaks older version subschema[1.29] with react 0.14.8

### ISSUE THREAD

**Issue by ksubramaniam78** [subschema/subschema-injection#1]
Hi Justin,

How are you? 

As we encountered some issues with your recent upgrade to use react 15.0.2 on subschema [btw, we will be upgrading to 15.0.2 shortly but we didn't have a chance to resolve this yet], we restricted ourselves temporarily to use subschema@1.2.9 [which uses react@0.14.8]. But with your recent update to subschema-injection to use react@15.0.2 with patch version this breaks the dependency. can you resolve this with a minor version change on subschema-injection and release another patch version with react@0.14.8 to address this for now? btw, for now we are restricting ourselves to use subschema-injection@1.2.2.

Thanks
Kumar

**Comment by jspears** [comment]
Hey Kumar,

Made react dep a wild card should fix.     Please file issues if with the subschema 1.3 series, if you run into.  Will probably start doing this for all the deps.

**Comment by ksubramaniam78** [comment]
Thanks Justin ! Sure will do.
